#!/bin/bash


# check if $1 is a valid dot separated ip address
function is_valid_ip()
{
    local  ip=$( echo $1 | cut -d"/" -f1 )
    local  mask=$( echo $1 | cut -d"/" -f2 )
    local  stat_ip=1
    local  stat_mask=1

    if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        OIFS=$IFS
        IFS='.'
        ip=($ip)
        IFS=$OIFS
        [[ ${ip[0]} -le 255 && ${ip[1]} -le 255 \
            && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]
        stat_ip=$?
    fi
    return $stat_ip
}

#check if $1 is a valid scp url
function is_valid_scp_url()
{
	echo "$1" | grep '^scp://.*:.*'  > /dev/null 2>&1
}
