#!/bin/sh
# set domain
# @param $1: system:	 	statical part of command
# @param $2: domain:		statical part of command
# @param $3: domain value:	the domain

. ${__cm_lib_dir}/cmlib

command=$(__cm_command $@)
command_path=$(__cm_command_path $@)
param=$(__cm_command_param $@)
command_path_dir=$(__cm_command_path_dir $@)
command_name=$(__cm_command_name $@)

nameserver=$(__cm_db_get_leaf system name-server 2>/dev/null) 
[ -n "$nameserver" ] && nameserver="namserver $nameserver"

echo "# modified by cm" > /etc/resolv.conf

if [ $__cm_no_command ]; then
	__cm_db_remove_leaf system domain
	echo "$nameserver" >> /etc/resolv.conf
else
	__cm_db_set_leaf "$param" system domain


	cat << EOF >> /etc/resolv.conf
domain $param
$nameserver
EOF

fi
