install:
	install -D $(BUILDDIR)/cmrc $(PREFIX)/etc/cm/cmrc
	install -D bin/cm $(PREFIX)/bin/cm
	install -d config-libexec $(PREFIX)/usr/lib/cm/config-libexec
	install -d libexec $(PREFIX)/usr/lib/cm/libexec
	install -d lib $(PREFIX)/usr/lib/cm/lib
	mkdir -p $(PREFIX)/var/lib/cmdb/

